spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password:
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 81
